### ISSUE TITLE
Выбранные в GUI аватарки подменяются на другие

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#1]
В режиме нон-стим не ставятся выбранные из стандартных в GUI аватарки, при заходе на сервер меняются на рандомные. Иногда случайным
образом меняются при перезаходе на сервер.

**Comment by Nord1cWarr1or** [comment]
На Windows не удалось воспроизвести. Видимо, происходит только на Linux. (конкретно я запускаю через PortProton)

**Comment by s1lentq** [comment]
Исправлено в Release 2.4.0.0
