### ISSUE TITLE
При отсутствии места в хранилище скачиваются пустые файлы

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#10]
### Описание:
При отсутствии места в хранилище, при загрузке файлов с сервера - скачиваются пустые файлы.

### Ожидаемый результат:
При отсутствии места файлы не скачиваются.

### Дополнительно:
Можно добавить показ соответствующей ошибки, конктрено о том, что закончилось место, в GUI или хотя бы в коносли.

**Comment by s1lentq** [comment]
Добавлено в Beta от 2.3.0.0

Если файл действительно не сможет записаться на диск, в консоль покажет сообщение
`Failed to save cstrike_download/maps/zp_oldstreet3_cso.bsp to disk`

Предполагаемое исправление:

В `DownloadManager::OnHTTPRequestCompleted` добавить следующий код
![image](https://github.com/g-asm/GoldSrc-Tracker/assets/5860435/f7b1efa4-6bd3-4537-99b5-a906e6b0cb14)
