### ISSUE TITLE
Добавить в GUI возможность изменять цвет граффити цветовой палитрой

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#13]
Добавить в GUI возможность изменять цвет граффити с помощью цветовой палитры, как сделано с дымовой гранатой.

**Comment by s1lentq** [comment]
Исправлено в Release 2.4.0.0

<details>

[![preview][1]][1]

[1]: https://github.com/user-attachments/assets/ef758e5a-c4e3-4261-b58f-d986219beecf

</details>
