### ISSUE TITLE
Вынести в GUI настройки обводки киллфида

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#14]
Вынести в GUI настройки обводки киллфида. (квар `hud_deathnotice_effect`)

**Comment by s1lentq** [comment]
Добавлено в Beta от 2.3.0.0
В разделе Настройки -> HUD -> Уведомления о смерти

![image](https://github.com/g-asm/GoldSrc-Tracker/assets/5860435/6502bfdf-382b-48de-87d4-ba068b31d490)
