### ISSUE TITLE
Не видно друзей на вкладке "Друзья" в сервербраузере

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#2]
### Описание:
В режиме Steam на вкладке "Друзья" в сервербраузере не видно серверов, где играют друзья из Steam.

### Ожидаемый результат:
Видно сервера, где играют друзья, как в оригинальном steam клиенте.

**Comment by s1lentq** [comment]
Исправлено в Beta от 2.3.0.0
