### ISSUE TITLE
Добавить возможность запуска анимаций осмотра на клиент-сайде

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#20]
Добавить возможность запуска анимаций осмотра на клиент-сайде, если они есть в модели. Сделать отдельную команду для этого.
Пример реализации есть в проекте [csldr](https://github.com/mikkokko/csldr).

**Comment by Nord1cWarr1or** [comment]
В клиент можно добавить стандартные модели оружий, но с анимациями осмотра. Такой пак есть на gamebanana.
Можно пойти ещё дальше и сделать этот пак применяемым по чекбоксу в GUI.

**Comment by s1lentq** [comment]
Добавлено в Beta 2.3.3.0
