### ISSUE TITLE
Не отображается причина отключения с сервера

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#22]
При кике или отключении с сервера не вручную, не пишется причина в всплывающей табличке.

![изображение](https://github.com/g-asm/GoldSrc-Tracker/assets/47604048/adb43158-4f9a-4d79-a244-8a3be2d19aff)

![изображение](https://github.com/g-asm/GoldSrc-Tracker/assets/47604048/69afe56a-be95-435d-b351-15f6e4a5370a)

### Ожидаемый результат
Как в ванильном клиенте, надпись в всплывающей табличке с причиной.

![изображение](https://github.com/g-asm/GoldSrc-Tracker/assets/47604048/489d6c6d-e58e-442d-a6b2-0b2a04e2c220)

**Comment by s1lentq** [comment]
Исправлено в Beta 2.3.0.0
