### ISSUE TITLE
Не работает автодополнение команд в консоли на кнопку space

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#23]
В оригинальном клиенте при вводе части команды и нажатии пробела, в консоль вставляется первая команда из выпадающего списка и вставляется пробел за ней.

![изображение](https://github.com/g-asm/GoldSrc-Tracker/assets/47604048/1eedfc65-e082-4d54-b763-93062d953d13)

![изображение](https://github.com/g-asm/GoldSrc-Tracker/assets/47604048/c1ecc00a-d571-4fad-9948-ff58ac9729f0)

**Comment by s1lentq** [comment]
Это поведение при нажатии "пробела" было удалено в пользу другого поведения - на поиск похожих команд и строк, для авто-завершения используется классический TAB.
