### ISSUE TITLE
Сделать возможность отключать shifting view модели

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#27]
Пример реализации есть в проекте [csldr](https://github.com/mikkokko/csldr). (`viewmodel_shift`)
Настройку можно вынести в GUI.

**Comment by s1lentq** [comment]
Добавлено в Beta 2.3.8.0
```
viewmodel_shift 1
viewmodel_shift_left_amt 1.5
viewmodel_shift_right_amt 0.75
```
