### ISSUE TITLE
Квар `scoreboard_showavatars 0` срабатывает только после перезахода на сервер

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#28]
На ванильном клиенте - сразу. И реализован он не лучшим способом - скрывает левую часть таблицы с аватарками. Гораздо красивее было бы оставить там пустое место, как если бы ни у кого их не было, а автарки скрыть.

**Comment by s1lentq** [comment]
Исправлено в Beta 2.3.2.0
