### ISSUE TITLE
Недоработка квара `scoreboard_showmoney 0`

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#29]
При значении 0 скрываются только сами знечения денег в таблице, остаётся пустое место и заголовок столбца "Деньги". А долно быть так, что столбец полностью пропадает, а "Здоровье" сдвигается вправо, на его место.

**Comment by s1lentq** [comment]
Исправлено в Beta 2.3.0.0
