### ISSUE TITLE
Сделать FOV для view модели отдельным

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#36]
Пример реализации есть в проекте [csldr](https://github.com/mikkokko/csldr). (viewmodel_fov)
Настройку можно вынести в GUI.

**Comment by s1lentq** [comment]
Добавлено в Beta 2.3.8.0
`viewmodel_fov 1.0 - 179.0` (По умолчанию 90)
