### ISSUE TITLE
Сделать обработку квара `sv_skyname` в реальном времени

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#37]
Сейчас, если на сервере сменилось небо, оно меняется на клиенте только при перезаходе.
Нужно будет добавить проверку на наличие текстур неба на клиенте, и если они есть, тогда менять не дожидаясь переподключения.

**Comment by s1lentq** [comment]
Добавлено в Beta 2.3.3.0
