### ISSUE TITLE
Добавить оповещение о спавне игрока при свёрнутой игре

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#39]
Сделать, например, звук. Вынести настройку в GUI.
Или: в чите HPP есть настройка "Разворачивать игру при спавне" — можно сделать такое.

**Comment by s1lentq** [comment]
Добавлено в Beta 2.3.7.0
`ui_window_bringfront_on_event 0/1`
`ui_window_sound_on_event 0/1`
