### ISSUE TITLE
Неправильное отображение большого кол-ва денег в HUD

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#4]
Количество денег в HUD имеет неправильную позицию, вследствии чего количество денег свыше 99999$ слегка залазит на границу экрана, а свыше 999999$ вообще выходит за пределы экрана.

120001 $:

![изображение](https://user-images.githubusercontent.com/47604048/236807339-4ad8e986-72d5-47fc-865e-66e0f9453a9c.png)

**Comment by s1lentq** [comment]
Исправлено в Release 2.4.0.0

<details>

[![preview][1]][1]

[1]: https://github.com/user-attachments/assets/83f26590-bb3e-40c9-a6a1-6f58b8c84daf

</details>
