### ISSUE TITLE
Сделать функционал смены боди view модели в зависимости от команды

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#45]
Пример реализации есть в проекте [csldr](https://github.com/mikkokko/csldr).
Нужно будет так же сделать, чтобы данный функционал применялся исключительно к стандартным моделям, иначе будут проблемы на модовых серверах.
На gamebanana есть как минимум два пака стандартных моделей оружий с КТ руками, можно будет добавить их в клиент.
И добавить квар/чекбокс в GUI на отключение этого функционала.

**Comment by s1lentq** [comment]
Добавлено в Beta 2.3.3.0
