### ISSUE TITLE
Голосовой чат пропадает при переключении view entity игрока

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#46]
Если кто-то говорит в микрофон, и в этот момент переключить view entity, есть шанс того, что этого игрока перестанет быть слышно. Исправляется командой stopsound.

**Comment by s1lentq** [comment]
Исправлено в Beta 2.3.0.0

Предполагаемое исправление

![image](https://github.com/g-asm/GoldSrc-Tracker/assets/5860435/f68aaac3-1d95-4b10-b320-602f68383a24)
