### ISSUE TITLE
Квар `scoreboard_showhealth 0` ломает таблицу счёта

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#5]
С правой стороны остаётся виден только столбец "Счёт", а "Смерти" и "Пинг" - отрезаются, так же нет надписи "Деньги" над соответствующим столбцом. После переподключения к серверу почти всё нормально: нет только надписи "Деньги".

![изображение](https://user-images.githubusercontent.com/47604048/236836664-246ecf3a-35ca-412d-a5bf-d5f62017065b.png)

Обновлено: в ванильной версии игры квар работает "на лету".

**Comment by s1lentq** [comment]
Исправлено в Beta 2.3.0.0
