### ISSUE TITLE
Декали на клиенте отрисовываются с отдачей при "зажиме" из AWP с прицелом

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#54]
Если войти в прицел и зажать кнопку атаки с AWP, пуля будет лететь прямо, но на клиенте декали будут отрировываться так, как будто стреляю без прицела.

**Comment by s1lentq** [comment]
Исправлено в Beta 2.3.5.0

Предполагаемое исправление в `CBasePlayerWeapon::ItemPostFrame`
![image](https://github.com/g-asm/GoldSrc-Tracker/assets/5860435/855fae55-cea1-4acb-8102-2f647a68f7ce)
