### ISSUE TITLE
Сделать квар `cl_minmodels_weapon`

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#56]
Добавить новый квар. например, `cl_minmodels_weapon`. Суть заключается в следующем - квар будет заниматься тем же самым, что и `cl_minmodels`, только для v_ моделей оружия. Иными словами, позволит для себя отключать видимость view моделей, выставленных с сервера, и видеть вместо них стандартные модели оружия.

**Comment by s1lentq** [comment]
Добавлено в Beta 2.3.7.0
`cl_minviewmodel 0/1`
