### ISSUE TITLE
Скорректировать русскую локализацию

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#57]
1. При использовании команды `ignorerad`: "_Теперь ПРИНИМАЕТ радиосообщения_" -> "_Теперь ПРИНИМАЮТСЯ радиосообщения_". (надпись по цетру)
2. При подключении игрока к серверу: "_%n подключается_" -> "_%n подключился_". Игрок уже зашёл, глагол должен быть в прошедшем времени. (в консоли)

**Comment by s1lentq** [comment]
Исправлено в Beta 2.3.7.0
