### ISSUE TITLE
VGUI меню покупки экипировки через `buyequip` остаётся старым при смене команды

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#59]
Если зайти сначала за одну команду, открыть меню экипировки через команду `buyequip`, потом сменить команду, и зайти в это же меню, то меню будет отображаться для старой команды. 
При переходе в меню экипировки из основного меню закупки, такого бага нет.

**Comment by s1lentq** [comment]
Исправлено в Beta 2.3.7.0
