### ISSUE TITLE
При не стандартном `viewmodel_fov` при прицеливании с aug/sg552 fov вьюмодели не меняется

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#61]

**Comment by Nord1cWarr1or** [comment]
### Шаги воспроизведения:

1. Задать `viewmodel_fov` больше или меньше 90
2. Прицелиться с AUG или SG552

### Ожидаемый результат:
https://github.com/g-asm/GoldSrc-Tracker/assets/47604048/d80f3f72-524b-478c-b2d6-1ee7fa0edc20
(FOV view модели подстраивается под FOV игрока)

### Фактический результат:
https://github.com/g-asm/GoldSrc-Tracker/assets/47604048/8101ed16-f3c7-4693-b98e-bd50af8b3154
(FOV view модели остаётся неизменным)

**Comment by s1lentq** [comment]
Исправлено в Beta 2.5.0.0
