### ISSUE TITLE
Двойной ассист в киллфиде (от regame + от плагина)

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#63]
![изображение](https://github.com/g-asm/GoldSrc-Tracker/assets/47604048/2476dcc7-b192-4c83-99a2-a2aad9f210b0)

**Comment by s1lentq** [comment]
Исправлено в 2.4.0.0

**Comment by s1lentq** [comment]
Исправлено в Beta 2.5.0.0
