### ISSUE TITLE
При использовании `viewmodel_retract` модель реагирует на неосязаемые границы энтити `cycler`

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#64]
![Screenshot_991](https://github.com/g-asm/GoldSrc-Tracker/assets/47604048/0b631be2-d7cd-410d-acb6-4df02d47f595)

Видео: 
https://github.com/g-asm/GoldSrc-Tracker/assets/47604048/4d11dffb-7631-4ee3-a8c7-f8974c768f47

Использованная карта: 35hp_xtreme_2019

**Comment by s1lentq** [comment]
Исправлено в 2.4.0.0
