### ISSUE TITLE
При различии карты между клиентом и сервером, причина кика в диалоговом окне не отображается

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#67]
**Ожидаемый результат:**
Причина кика пишется в табличке

**Фактический результат:**
`Your map [maps/35hp_xtreme_2019.bsp] differs from the server's.` - пишется только в консоли.

![изображение](https://github.com/g-asm/GoldSrc-Tracker/assets/47604048/f3fce62b-deff-4456-9552-746f093ee17a)

**Comment by s1lentq** [comment]
Исправлено в Beta 2.4.5.2
