### ISSUE TITLE
Появляется muzzleflash при быстрой смене оружия при `cl_minviewmodel 1`

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#69]
Появляется muzzleflash при быстрой смене оружия, предположительно, на нож, и предположительно, при `cl_minviewmodel 1` и если модель оружия была подменена.

Видео:

https://github.com/user-attachments/assets/a08432b7-3857-4513-8b8b-93082fa7d8e1

**Comment by s1lentq** [comment]
Исправлено в Beta 2.5.0.0
