### ISSUE TITLE
Название сервера в scoreboard слишком короткое

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#7]
Название сервера в scoreboard слишком короткое, не отображается полностью при длинном названии.

**Comment by Nord1cWarr1or** [comment]
Уже исправлено.

**Comment by s1lentq** [comment]
Предполагаемое исправление в `CCSClientScoreBoardDialog::Update`
![image](https://github.com/g-asm/GoldSrc-Tracker/assets/5860435/a526e4cd-81c3-46b9-b370-333bca692c37)
