### ISSUE TITLE
Отсутствует кнопка "Добавить текущий сервер" в избранном в сервербраузере

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#70]
### Описание
Отсутствует кнопка "Добавить текущий сервер" на вкладке "Избранное" в сервербраузере.

### Ожидаемый результат
Наличие на нижней панели сервербраузера кнопки "Добавить текущий сервер", которая добавляет сервер, на котором сейчас находится игрок, в избранное.
Такая кнопка присутствует в лицензионном клиенте.

### Фактический результат
Кнопка отсутствует.

### Дополнительно
Наличие такой кнопки в лицензионном клиенте:

![image](https://github.com/user-attachments/assets/09d53c19-db1d-4e59-b79d-b6e7bd6b25e4)
(кнопка не активна из-за того, что клиент не находится на сервере)

**Comment by s1lentq** [comment]
Исправлено в Beta 2.5.0.1
