### ISSUE TITLE
Звук падающих гильз распространяется на большее расстояние, чем звук выстрела оружий с глушителем 

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#71]
### Ожидаемый результат
Звук падающих гильз распространяется на расстояние, равное или даже меньшее, чем звук выстрела, имеющий наименьшее затухание (attenuation).

### Фактический результат
Звуки падающих гильз слышен на большем расстоянии, чем звук выстрелов оружий с глушителем.

**Comment by s1lentq** [comment]
Исправлено в Beta 2.5.0.1
