### ISSUE TITLE
Игроки видны через дым на новом типе радара

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#73]
### Описание
Игроки видны через дым на новом типе радара `hud_radar 1`. 

### Ожидаемый результат
Игроки, которые находятся в зоне видимости, но за облаком дыма, не отображаются на радаре.

### Фактический результат
Игроки в зоне видимости всегда отображаются на радаре.

### Дополнительно
![изображение](https://github.com/user-attachments/assets/583e314e-6f85-4041-b9ab-37c7cd716d2c)

**Comment by s1lentq** [comment]
Исправлено в Beta 2.5.0.2
