### ISSUE TITLE
Игроки видны в полной темноте на новом типе радара

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#74]
### Описание
Игроки видны в полной темноте (LightStyle "a") на новом типе радара `hud_radar 1`. 

### Ожидаемый результат
Игроки, которые находятся в полной темноте (LightStyle "a"), не отображаются на радаре. Отображаются, если они освещены фонариком, или DynamicLight, или если у игрока есть ПНВ.

### Фактический результат
Игроки в зоне видимости всегда отображаются на радаре.

### Дополнительно
![изображение](https://github.com/user-attachments/assets/ba7ba24f-26e9-4929-8dcc-134c2a2b3764)

**Comment by s1lentq** [comment]
Исправлено в Beta 2.5.0.2
