### ISSUE TITLE
Возможность блокировать HUD и DHUD сообщения

### ISSUE THREAD

**Issue by Nord1cWarr1or** [goldclient-plus/GoldSrc-Tracker#8]
Добавить возможность (например квар и/или вынести в GUI) блокировать входящие HUD и DHUD сообщения на клиенте. На некоторых серверах мешают играть + садят ФПС на слабых ПК.

**Comment by s1lentq** [comment]
На данный момент в Beta 2.3.0.0 реализован только CVar

```
hud_message - Show HUD messages
0 = Disabled
1 = Display all messages (Default)
2 = Only HUD messages
3 = Only DHUD messages
```
